from django.contrib import admin
from django import forms
from home.models import Blog, AboutMe, Skill, Project
from django.utils.html import format_html
from django_ckeditor_5.widgets import CKEditor5Widget

# Register your models here.
class BlogAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditor5Widget(config_name='default'))

    class Meta:
        model = Blog
        fields = "__all__"
    
    def clean_content(self):
        """Convert YouTube watch URLs to embed URLs and ensure proper iframe format"""
        content = self.cleaned_data.get('content', '')
        if content:
            import re

            def time_to_seconds(time_str):
                if not time_str:
                    return None
                time_str = time_str.strip()
                if time_str.isdigit():
                    return int(time_str)
                match = re.match(r'(?:(\d+)h)?(?:(\d+)m)?(?:(\d+)s)?$', time_str)
                if not match:
                    return None
                hours = int(match.group(1) or 0)
                minutes = int(match.group(2) or 0)
                seconds = int(match.group(3) or 0)
                total = (hours * 3600) + (minutes * 60) + seconds
                return total if total > 0 else None

            def build_embed_url(video_id, time_str):
                base = f"https://www.youtube.com/embed/{video_id}"
                start_seconds = time_to_seconds(time_str)
                if start_seconds is None:
                    return base
                return f"{base}?start={start_seconds}"

            def add_rel_param(url):
                if 'rel=' in url:
                    return url
                separator = '&' if '?' in url else '?'
                return f"{url}{separator}rel=0"

            def ensure_iframe_attr(tag, attr, value=None):
                if attr == 'allowfullscreen':
                    if re.search(r'\ballowfullscreen\b', tag, re.IGNORECASE):
                        return tag
                    return tag[:-1] + ' allowfullscreen>'
                if re.search(rf'\b{attr}\s*=', tag, re.IGNORECASE):
                    return tag
                return tag[:-1] + f' {attr}="{value}">'
            
            # Convert watch URLs to embed URLs (for media plugin)
            content = re.sub(
                r'https://www\.youtube\.com/watch\?v=([a-zA-Z0-9_-]+)(?:&t=([0-9hms]+))?',
                lambda match: build_embed_url(match.group(1), match.group(2)),
                content
            )
            
            # Also handle youtu.be short URLs
            content = re.sub(
                r'https://youtu\.be/([a-zA-Z0-9_-]+)(?:\?t=([0-9hms]+))?',
                lambda match: build_embed_url(match.group(1), match.group(2)),
                content
            )

            # Normalize embed URLs that use ?t=
            content = re.sub(
                r'https://www\.youtube\.com/embed/([a-zA-Z0-9_-]+)\?t=([0-9hms]+)',
                lambda match: build_embed_url(match.group(1), match.group(2)),
                content
            )

            # Ensure rel=0 for YouTube embed URLs
            content = re.sub(
                r'https://www\.youtube\.com/embed/[a-zA-Z0-9_-]+(?:\?[^"\s>]*)?',
                lambda match: add_rel_param(match.group(0)),
                content
            )

            # Ensure iframe attributes needed for YouTube playback
            def augment_iframe(match):
                tag = match.group(0)
                if 'youtube.com/embed' not in tag:
                    return tag
                tag = ensure_iframe_attr(
                    tag,
                    'allow',
                    'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share'
                )
                tag = ensure_iframe_attr(tag, 'referrerpolicy', 'strict-origin-when-cross-origin')
                tag = ensure_iframe_attr(tag, 'title', 'YouTube video player')
                tag = ensure_iframe_attr(tag, 'frameborder', '0')
                tag = ensure_iframe_attr(tag, 'allowfullscreen')
                return tag

            content = re.sub(r'<iframe[^>]*>', augment_iframe, content, flags=re.IGNORECASE)
        return content


class BlogAdmin(admin.ModelAdmin):
    form = BlogAdminForm
    # make autogenerated fields read-only to avoid FieldError
    readonly_fields = ('thumbnail_preview', 'time')
    fieldsets = (
        (None, {'fields': ('title','meta','content','category','slug')}),
        ('Meta', {'fields': ('time',)}),
        ('Thumbnail', {'fields': ('thumbnail_img','thumbnail_url','thumbnail_preview')}),
    )

    @admin.display(description='Current thumbnail')
    def thumbnail_preview(self, obj):
        if obj.thumbnail_img:
            return format_html('<img src="{}" style="max-width: 200px; height: auto;" />', obj.thumbnail_img.url)
        elif obj.thumbnail_url:
            return format_html('<img src="{}" style="max-width: 200px; height: auto;" />', obj.thumbnail_url)
        return '(No image)'

admin.site.register(Blog, BlogAdmin)


class AboutMeAdminForm(forms.ModelForm):
    bio = forms.CharField(widget=CKEditor5Widget(config_name='default'))

    class Meta:
        model = AboutMe
        fields = "__all__"


class AboutMeAdmin(admin.ModelAdmin):
    """Admin for singleton AboutMe model"""
    form = AboutMeAdminForm
    readonly_fields = ('profile_image_preview',)
    fieldsets = (
        ('Personal Info', {'fields': ('name', 'profession', 'email', 'phone')}),
        ('About', {'fields': ('bio',)}),
        ('Profile Image', {'fields': ('profile_image_url', 'profile_image_preview')}),
        ('Social Links', {'fields': ('linkedin_url', 'github_url', 'telegram_url', 'x_url', 'leetcode_url')}),
    )

    def has_add_permission(self, request):
        """Limit to one instance only"""
        if AboutMe.objects.exists():
            return False
        return super().has_add_permission(request)

    @admin.display(description='Profile Image Preview')
    def profile_image_preview(self, obj):
        if obj and obj.profile_image_url:
            return format_html('<img src="{}" style="max-width: 200px; height: auto; border-radius: 50%;" />', obj.profile_image_url)
        return '(No image)'


class SkillAdmin(admin.ModelAdmin):
    """Admin for Skill model"""
    list_display = ['name', 'percentage', 'order']
    list_editable = ['order']
    list_filter = ['percentage']
    search_fields = ['name']


class ProjectAdmin(admin.ModelAdmin):
    """Admin for Project model"""
    list_display = ['title', 'order', 'created_at']
    list_editable = ['order']
    readonly_fields = ('thumbnail_preview', 'created_at')
    fieldsets = (
        ('Basic Info', {'fields': ('title', 'description')}),
        ('Media', {'fields': ('thumbnail_url', 'thumbnail_preview')}),
        ('Links', {'fields': ('github_link', 'demo_link')}),
        ('Technical', {'fields': ('technologies',)}),
        ('Meta', {'fields': ('order', 'created_at')}),
    )
    search_fields = ['title', 'description', 'technologies']

    @admin.display(description='Thumbnail Preview')
    def thumbnail_preview(self, obj):
        if obj and obj.thumbnail_url:
            return format_html('<img src="{}" style="max-width: 200px; height: auto;" />', obj.thumbnail_url)
        return '(No image)'


admin.site.register(AboutMe, AboutMeAdmin)
admin.site.register(Skill, SkillAdmin)
admin.site.register(Project, ProjectAdmin)
