from django.contrib import admin
from django import forms
from home.models import Blog

# Register your models here.
class BlogAdminForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'id': "richtext_field"}))

    class Meta:
        model = Blog
        fields = "__all__"

from django.utils.html import format_html

class BlogAdmin(admin.ModelAdmin):
    form = BlogAdminForm
    # make autogenerated fields read-only to avoid FieldError
    readonly_fields = ('thumbnail_preview', 'time')
    fieldsets = (
        (None, {'fields': ('title','meta','content','category','slug')}),
        ('Meta', {'fields': ('time',)}),
        ('Thumbnail', {'fields': ('thumbnail_img','thumbnail_url','thumbnail_preview')}),
    )

    @admin.display(description='Current thumbnail')
    def thumbnail_preview(self, obj):
        if obj.thumbnail_img:
            return format_html('<img src="{}" style="max-width: 200px; height: auto;" />', obj.thumbnail_img.url)
        elif obj.thumbnail_url:
            return format_html('<img src="{}" style="max-width: 200px; height: auto;" />', obj.thumbnail_url)
        return '(No image)'

admin.site.register(Blog, BlogAdmin)