# Generated by Django 4.1.4 on 2023-01-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='remark',
            field=models.TextField(null=True, unique=True),
        ),
    ]
