# Generated by Django 6.0.2 on 2026-02-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutme_project_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='twitter_url',
            new_name='leetcode_url',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='x_url',
            field=models.URLField(blank=True, help_text='X (formerly Twitter) profile URL'),
        ),
    ]
