# Generated by Django 6.0.2 on 2026-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_twitter_url_aboutme_leetcode_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
